config/routes.rb
Rails.application.routes.draw do
  # Admin constraint
  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  read_only_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.read_only?
  end

  non_admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && !request.env['warden'].user.admin? && !request.env['warden'].user.read_only?
  end
  authenticated_constraint = lambda do |request|
    request.env['warden'].authenticate?
  end

  # This needs to be firt, but *before* admin and user contrained routes are configured
  devise_for :users

  constraints(read_only_constraint || admin_constraint) do
    root to: 'hyrax/dashboard#show'

    concern :exportable, Blacklight::Routes::Exportable.new
    concern :searchable, Blacklight::Routes::Searchable.new

    # Only admin users should be able to search
    resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
      concerns :searchable
    end
    mount BlacklightAdvancedSearch::Engine => '/'

    # Mount sidekiq web ui and require authentication by an admin user
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    resources :batches, controller: 'hyrax/batches', only: [:index, :show, :create]
    resources :eads, only: [:index]
    resources :metadata_exports,
              controller: 'hyrax/metadata_exports',
              only:       [:create]
    resources :metadata_imports,
              controller: 'hyrax/metadata_imports',
              only:       [:new, :create]
    resources :xml_imports,
              controller: 'hyrax/xml_imports',
              only:       [:show, :create, :new, :edit, :update]
    resources :templates,
              controller: 'hyrax/templates',
              only:       [:index, :destroy, :edit, :update, :new]
    resources :template_updates,
              controller: 'hyrax/template_updates',
              only:       [:index, :new, :create]

    get '/metadata_exports/:id/download', to: 'hyrax/metadata_exports#download'

    # Routes for managing drafts
    post '/draft/save_draft/:id', to: 'tufts/draft#save_draft'
    post '/draft/delete_draft/:id', to: 'tufts/draft#delete_draft'
    get '/draft/draft_saved/:id', to: 'tufts/draft#draft_saved'

    # Routes for managing QR status
    resources :qr_statuses, controller: 'tufts/qr_status', only: [:set_status, :status] do
      member do
        post 'set_status'
        get 'status'
      end
    end

    # Routes for managing publication status
    resources :publication_statuses, controller: 'tufts/publication_status', only: [:publish, :unpublish, :status] do
      member do
        post 'publish'
        post 'unpublish'
        get 'status'
      end
    end

    resources :deposit_types do
      get 'export', on: :collection
    end

    # Routes for managing QR status

    get '/handle/log/', to: 'tufts/handle_log#index'
  end # end admin constraint

  constraints non_admin_constraint do
    root to: 'contribute#redirect'
    get '/dashboard', to: 'contribute#redirect'
  end

  constraints authenticated_constraint do
    resources :users
    # Mount Engines
    mount Blacklight::Engine => '/'
    mount Hydra::RoleManagement::Engine => '/'
    mount Qa::Engine => '/authorities'
    mount Hyrax::Engine, at: '/'

    # Home page for non-authenticated users
    resources :welcome, only: 'index'
    root 'hyrax/homepage#index'

    curation_concerns_basic_routes

    resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      concerns :exportable
    end

    resources :bookmarks do
      concerns :exportable

      collection do
        delete 'clear'
      end
    end
  end

  # Unauthenticated users should only be able to reach the /contribute controller and the log in page
  deployed_as_dark_archive = ActiveModel::Type::Boolean.new.cast(ENV['DEPLOY_AS_DARK_ARCHIVE'])
  unless deployed_as_dark_archive
    resources :contribute, as: 'contributions', controller: :contribute, only: [:index, :new, :create, :redirect] do
      collection do
        get 'license'
      end
    end
  end

  if deployed_as_dark_archive
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  else
    root to: 'contribute#redirect'
    get '*path' => redirect { 'contribute#redirect' }
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  include BlacklightAdvancedSearch::Controller
  include Hydra::Catalog
  include Hydra::Controller::ControllerBehavior
  # This filter applies the hydra access controls
  before_action :enforce_show_permissions, only: :show

  def self.uploaded_field
    solr_name('system_create', :stored_sortable, type: :date)
  end

  def self.modified_field
    solr_name('system_modified', :stored_sortable, type: :date)
  end

  configure_blacklight do |config|
    # default advanced config values
    config.http_method = :post
    config.advanced_search ||= Blacklight::OpenStructWithHashAccess.new
    config.advanced_search[:url_key] ||= 'advanced'
    config.advanced_search[:query_parser] ||= 'dismax'
    config.advanced_search[:form_solr_parameters] ||= {}

    config.view.gallery.partials = [:index_header, :index]
    config.view.masonry.partials = [:index]
    config.view.slideshow.partials = [:index]

    config.show.tile_source_field = :content_metadata_image_iiif_info_ssm
    config.show.partials.insert(1, :openseadragon)

    config.search_builder_class = TuftsCatalogSearchBuilder
    #     config.search_builder_class = Hyrax::CatalogSearchBuilder
    # Show gallery view
    config.view.gallery.partials = [:index_header, :index]
    config.view.slideshow.partials = [:index]

    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = {
      qt: "search",
      rows: 10,
      qf: "title_tesim description_tesim creator_tesim keyword_tesim"
    }

    # Add larger pagination options to support Tufts batch
    config.per_page = [10, 20, 50, 100, 500, 1000]
    config.max_per_page = config.per_page.max

    # solr field configuration for document/show views
    config.index.title_field = solr_name("title", :stored_searchable)
    config.index.display_type_field = solr_name("has_model", :symbol)
    config.index.thumbnail_field = 'thumbnail_path_ss'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    config.add_facet_field solr_name("human_readable_type", :facetable), label: "Type", limit: 5
    config.add_facet_field solr_name("resource_type", :facetable), label: "Resource Type", limit: 5
    config.add_facet_field solr_name("creator", :facetable), limit: 5, label: 'Creator'
    config.add_facet_field solr_name("contributor", :facetable), label: "Contributor", limit: 5
    config.add_facet_field solr_name("subject", :facetable), limit: 5, label: 'Subject'
    config.add_facet_field solr_name("language", :facetable), limit: 5, label: 'Language'
    config.add_facet_field solr_name("publisher", :facetable), limit: 5, label: 'Publisher'
    config.add_facet_field solr_name("file_format", :facetable), limit: 5, label: 'File Format'
    config.add_facet_field solr_name('member_of_collections', :symbol), limit: 5, label: 'Collections'
    config.add_facet_field solr_name("displays_in", :facetable), limit: 5, label: 'Displays In'
    config.add_facet_field solr_name("held_by", :facetable), limit: 5, label: 'Held By'

    # The generic_type isn't displayed on the facet list
    # It's used to give a label to the filter that comes from the user profile
    config.add_facet_field solr_name("generic_type", :facetable), if: false

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field solr_name("title", :stored_searchable), label: "Title", itemprop: 'name', if: false
    config.add_index_field 'id', label: 'ID'
    config.add_index_field solr_name("description", :stored_searchable), itemprop: 'description', helper_method: :iconify_and_mark_safe
    config.add_index_field solr_name("identifier", :stored_searchable), itemprop: 'description', helper_method: :iconify_auto_link

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different.
    #
    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise.
    config.add_search_field('all_fields', label: 'All Fields') do |field|
      all_names = config.show_fields.values.map(&:field).join(" ")
      title_name = solr_name("title", :stored_searchable)
      field.solr_parameters = {
        qf: %( #{all_names} id title_tesim description_tesim creator_tesim
        keyword_tesim abstract_tesim accrual_policy_tesim
        alternative_title_tesim audience_tesim contributor_tesim
        corporate_name_tesim created_by_tesim creator_dept_tesim
        primary_date_tesim date_accepted_tesim date_available_tesim
        date_copyrighted_tesim date_created_tesim date_issued_tesim
        date_modified_tesim date_uploaded_tesim description_tesim
        displays_in_tesim ead_tesim embargo_note_tesim end_date_tesim extent_tesim
        format_label_tesim funder_tesim genre_tesim geographic_name_tesim
        has_part_tesim internal_note_tesim
        is_part_of_tesim is_replaced_by_tesim language_tesim
        tufts_license_tesim license_tesim held_by_tesim identifier_tesim
        personal_name_tesim provenance_tesim publisher_tesim qr_note_tesim
        qr_status_tesim created_by_tesim rejection_reason_tesim replaces_tesim
        retention_period_tesim rights_statement_tesim rights_holder_tesim
        rights_note_tesim source_tesim spatial_tesim admin_start_date_tesim
        steward_tesim subject_tesim table_of_contents_tesim temporal_tesim
        legacy_pid_tesim resource_type_tesim tufts_is_part_of_tesim aspace_cuid_tesim
        oclc_tesim doi_tesim isbn_tesim dc_access_rights_tesim all_text_timv),
        pf: title_name.to_s
      }
    end

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields.
    # creator, title, description, publisher, date_created,
    # subject, language, resource_type, format, identifier, based_near,
    config.add_search_field('contributor') do |field|
      # solr_parameters hash are sent to Solr as ordinary url query params.

      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      solr_name = solr_name("contributor", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('creator') do |field|
      solr_name = solr_name("creator", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('batch') do |field|
      solr_name = solr_name('batch', :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('title') do |field|
      solr_name = solr_name("title", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('description') do |field|
      field.label = "Description"
      solr_name = solr_name("description", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('publisher') do |field|
      solr_name = solr_name("publisher", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('date_created') do |field|
      solr_name = solr_name("date_created", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('subject') do |field|
      solr_name = solr_name("subject", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('language') do |field|
      solr_name = solr_name("language", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('resource_type') do |field|
      solr_name = solr_name("resource_type", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('identifier') do |field|
      solr_name = solr_name("identifier", :stored_searchable)
      field.solr_local_parameters = {
        qf: solr_name,
        pf: solr_name
      }
    end

    config.add_search_field('depositor') do |field|

app/views/catalog/_batch_header.html.erb
<ul class="batch-controls">
  <li class="batch-check">
    <%= check_box_tag 'check_all', 'yes', @all_checked %>
  </li>
<% if current_user.admin? %>
  <li>
    <%= button_to "Apply Template", new_template_update_path, method: :get, class: "btn btn-primary submits-batches" %>
  </li>
  <li>
    <%= button_to "Publish", batches_path, method: :post, params: { batch: { batchable_attributes: { batch_type: "Publish" } } }, class: "btn btn-primary submits-batches" %>
  </li>
  <li>
    <%= button_to "Unpublish", batches_path, method: :post, params: { batch: { batchable_attributes: { batch_type: "Unpublish" } } }, class: "btn btn-primary submits-batches" %>
  </li>
<% end %>
  <li>
    <%= button_to "Export Metadata", metadata_exports_path, method: :post, class: "btn btn-primary submits-batches" %>
  </li>
  <li class="selected-documents">
    <div id="selected_documents_count">Number of documents selected: 0</div>
  </li>
</ul>

app/views/catalog/_search_form.html.erb
<%= form_tag search_form_action, method: :get, id: "search-form-header", role: "search" do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
  <%= hidden_field_tag :search_field, 'all_fields' %>
  <div class="input-group">

    <label class="sr-only" for="search-field-header"><%= t("hyrax.search.form.q.label", application_name: application_name) %></label>
    <%= text_field_tag :q, current_search_parameters , class: "q form-control", id: "search-field-header", placeholder: t("hyrax.search.form.q.placeholder") %>

    <div class="input-group-btn">
      <button type="submit" class="btn btn-primary" id="search-submit-header">
        <%= t('hyrax.search.button.html') %>
      </button>
      <% if current_user %>
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
          <span data-search-element="label"><%= t("hyrax.search.form.option.all.label_long", application_name: application_name) %></span>
          <span class="caret"></span>
        </button>

        <ul class="dropdown-menu pull-right">
          <li class="search-dropdown-js">
            <%= link_to t("hyrax.search.form.option.all.label_long", application_name: application_name), "#",
              data: { "search-option" => main_app.search_catalog_path, "search-label" => t("hyrax.search.form.option.all.label_short") } %>
          </li>
          <li class="search-dropdown-js" >
            <%= link_to t("hyrax.search.form.option.my_works.label_long"), "#",
              data: { "search-option" => hyrax.my_works_path, "search-label" => t("hyrax.search.form.option.my_works.label_short") } %>
          </li>
          <li class="search-dropdown-js">
            <%= link_to t("hyrax.search.form.option.my_collections.label_long"), "#",
              data: { "search-option" => hyrax.my_collections_path, "search-label" => t("hyrax.search.form.option.my_collections.label_short") } %>
          </li>
          <li class="search-dropdown-js">
            <%= link_to t("hyrax.search.form.option.my_shares.label_long"), "#",
              data: { "search-option" => hyrax.dashboard_shares_path, "search-label" => t("hyrax.search.form.option.my_shares.label_short") } %>
          </li>
          <li class="batch-search-dropdown-js">
           <%= link_to t("hyrax.search.form.option.batch"), "#",
             data: { "search-option" => main_app.search_catalog_path, "search-label" => t("hyrax.search.form.option.batch") } %>
            <script>
             BatchSelection.resetToAllFieldsOnTurboLinksLoad()
             BatchSelection.changeSearchFieldOnBatchSelect()
             BatchSelection.changeSearchFieldOnOtherSelect()
            </script>
          </li>
      <% end %>

        </ul>
    </div><!-- /.input-group-btn -->

  </div><!-- /.input-group -->
<% end %>