config/routes.rb
Rails.application.routes.draw do
  # Admin constraint
  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  read_only_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.read_only?
  end

  non_admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && !request.env['warden'].user.admin? && !request.env['warden'].user.read_only?
  end
  authenticated_constraint = lambda do |request|
    request.env['warden'].authenticate?
  end

  # This needs to be firt, but *before* admin and user contrained routes are configured
  devise_for :users

  constraints(read_only_constraint || admin_constraint) do
    root to: 'hyrax/dashboard#show'

    concern :exportable, Blacklight::Routes::Exportable.new
    concern :searchable, Blacklight::Routes::Searchable.new

    # Only admin users should be able to search
    resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
      concerns :searchable
    end
    mount BlacklightAdvancedSearch::Engine => '/'

    # Mount sidekiq web ui and require authentication by an admin user
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    resources :batches, controller: 'hyrax/batches', only: [:index, :show, :create]
    resources :eads, only: [:index]
    resources :metadata_exports,
              controller: 'hyrax/metadata_exports',
              only:       [:create]
    resources :metadata_imports,
              controller: 'hyrax/metadata_imports',
              only:       [:new, :create]
    resources :xml_imports,
              controller: 'hyrax/xml_imports',
              only:       [:show, :create, :new, :edit, :update]
    resources :templates,
              controller: 'hyrax/templates',
              only:       [:index, :destroy, :edit, :update, :new]
    resources :template_updates,
              controller: 'hyrax/template_updates',
              only:       [:index, :new, :create]

    get '/metadata_exports/:id/download', to: 'hyrax/metadata_exports#download'

    # Routes for managing drafts
    post '/draft/save_draft/:id', to: 'tufts/draft#save_draft'
    post '/draft/delete_draft/:id', to: 'tufts/draft#delete_draft'
    get '/draft/draft_saved/:id', to: 'tufts/draft#draft_saved'

    # Routes for managing QR status
    resources :qr_statuses, controller: 'tufts/qr_status', only: [:set_status, :status] do
      member do
        post 'set_status'
        get 'status'
      end
    end

    # Routes for managing publication status
    resources :publication_statuses, controller: 'tufts/publication_status', only: [:publish, :unpublish, :status] do
      member do
        post 'publish'
        post 'unpublish'
        get 'status'
      end
    end

    resources :deposit_types do
      get 'export', on: :collection
    end

    # Routes for managing QR status

    get '/handle/log/', to: 'tufts/handle_log#index'
  end # end admin constraint

  constraints non_admin_constraint do
    root to: 'contribute#redirect'
    get '/dashboard', to: 'contribute#redirect'
  end

  constraints authenticated_constraint do
    resources :users
    # Mount Engines
    mount Blacklight::Engine => '/'
    mount Hydra::RoleManagement::Engine => '/'
    mount Qa::Engine => '/authorities'
    mount Hyrax::Engine, at: '/'

    # Home page for non-authenticated users
    resources :welcome, only: 'index'
    root 'hyrax/homepage#index'

    curation_concerns_basic_routes

    resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      concerns :exportable
    end

    resources :bookmarks do
      concerns :exportable

      collection do
        delete 'clear'
      end
    end
  end

  # Unauthenticated users should only be able to reach the /contribute controller and the log in page
  deployed_as_dark_archive = ActiveModel::Type::Boolean.new.cast(ENV['DEPLOY_AS_DARK_ARCHIVE'])
  unless deployed_as_dark_archive
    resources :contribute, as: 'contributions', controller: :contribute, only: [:index, :new, :create, :redirect] do
      collection do
        get 'license'
      end
    end
  end

  if deployed_as_dark_archive
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  else
    root to: 'contribute#redirect'
    get '*path' => redirect { 'contribute#redirect' }
  end
end

app/models/collection.rb
# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer
end

app/controllers/hyrax/my/collections_controller.rb
module Hyrax
  module My
    class CollectionsController < MyController
      # Define collection specific filter facets.
      def self.configure_facets
        configure_blacklight do |config|
          # Name of pivot facet must match field name that uses helper_method
          config.add_facet_field Collection.collection_type_gid_document_field_name,
                                 helper_method: :collection_type_label, limit: 5,
                                 pivot: ['has_model_ssim', Collection.collection_type_gid_document_field_name],
                                 label: 'Collection Type'
          # This causes AdminSets to also be shown with the Collection Type label
          config.add_facet_field 'has_model_ssim',
                                 label: 'Collection Type',
                                 limit: 5, show: false
        end
      end
      configure_facets

      def search_builder_class
        Hyrax::My::CollectionsSearchBuilder
      end

      def index
        add_breadcrumb t(:'hyrax.controls.home'), root_path
        add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
        add_breadcrumb t(:'hyrax.admin.sidebar.collections'), hyrax.my_collections_path
        collection_type_list_presenter
        managed_collections_count
        super
      end

      private

        def search_action_url(*args)
          hyrax.my_collections_url(*args)
        end

        # The url of the "more" link for additional facet values
        def search_facet_path(args = {})
          hyrax.my_dashboard_collections_facet_path(args[:id])
        end

        def collection_type_list_presenter
          @collection_type_list_presenter ||= Hyrax::SelectCollectionTypeListPresenter.new(current_user)
        end

        def managed_collections_count
          @managed_collection_count = Hyrax::Collections::ManagedCollectionsService.managed_collections_count(scope: self)
        end
    end
  end
end

app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
<div role="dialog" class="modal collection-list-modal fade" id="collection-list-container" tabindex="-1" aria-labelledby="col_add_title" >
  <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <span class="modal-title" id="col_add_title"><%= t("hyrax.collection.select_form.title") %></span>
        </div>
        <div class="modal-body">
          <% if user_collections.blank? %>
            <em> <%= t("hyrax.collection.select_form.no_collections") %></em><br><br><br><br>
          <% else %>
            <div class="collection-list">
              <fieldset>
                <legend><%= t("hyrax.collection.select_form.select_heading") %></legend>
                <!-- 5/2018 - Customized view to sort collections alphabetically instead of by creation date -->
              <ul>
                <% alpha_user_collections.each_with_index do |collection,index|  %>
                  <li>
                    <% selected = (collection.id == @add_works_to_collection) || (@add_works_to_collection.blank? && index == 0) %>
                    <%= radio_button_tag(:id, collection.id, selected, class: "collection-selector") %>
                    <%= label_tag(:collection, collection.title_or_label, for: "id_#{collection.id}") %>
                  </li>
                <% end %>
              </ul>
              </fieldset>
            </div><!-- collection-list -->
          <% end %> <!-- else -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t("hyrax.collection.select_form.close")%></button>
          <% if user_collections.blank? %>
            <%= render 'hyrax/dashboard/collections/button_create_collection', label: t("hyrax.collection.select_form.create") %>

          <% else %>
            <%= render 'hyrax/dashboard/collections/button_for_update_collection', label: t("hyrax.collection.select_form.update"), collection_id: 'collection_replace_id' %>
            <%= render 'hyrax/dashboard/collections/button_create_collection', label: t("hyrax.collection.select_form.create_new") %>
          <% end %>
        </div>
      </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb
<% id = document.id %>
<tr id="document_<%= id %>">
  <td>&nbsp;
    <% if current_user and document.depositor != current_user.user_key %>
      <i class="glyphicon glyphicon-share-alt"/>
    <% end %>
  </td>
  <td>
    <div class="media"> 
    <% if document.collection? %>
     <div class="media-left">
      <%= render_thumbnail_tag document, { class: "hidden-xs file_listing_thumbnail" }, { suppress_link: true } %>
     </div>
     <div class="media-body">
        <h4 class="media-heading">
          <p><%= document.title_or_label %></p>          
        </h4>
        <%= render_collection_links(document) %>      
      </div>
    <% else %>
      <%= link_to [main_app, document], class: "media-left" do %>
        <%= render_thumbnail_tag document, { class: "hidden-xs file_listing_thumbnail" }, { suppress_link: true } %>
      <% end %>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to document.title_or_label, [main_app, document], id: "src_copy_link#{id}", class: "#{'document-title' if document.title_or_label == document.label}" %>
          <a href="#" class="small" title="Click for more details"><i id="expand_<%= id %>" class="glyphicon glyphicon-chevron-right"></i></a>
        </h4>
        <%= render_collection_links(document) %>
      <% end %>	
      </div>
    </div>
  </td>
  <td class="text-center"><%= document.date_uploaded %> </td>
  <td class="text-center">
    <%= render_visibility_link(document) %>
  </td>
  <% if current_user %>
    <% if document.collection? %>
      <td class="text-center">
        <p>Not Available</p>
      </td>
    <% else %>
    <td class="text-center">
      <%= render 'show_document_list_menu', document: document %>
    </td>
   <% end %>

  <% end %>
</tr>
<tr id="detail_<%= id %>"> <!--  document detail"> -->
  <td colspan="6">
    <dl class="expanded-details row">
      <dt class="col-xs-3 col-lg-2">Creator:</dt>
      <dd class="col-xs-9 col-lg-4"><%= document.creator.to_a.to_sentence %></dd>
      <dt class="col-xs-3 col-lg-2">Depositor:</dt>
      <dd class="col-xs-9 col-lg-4"><%= link_to_profile document.depositor %></dd>
      <dt class="col-xs-3 col-lg-2">Edit Access:</dt>
      <dd class="col-xs-9 col-lg-10">
        <% if document.edit_groups.present? %>
          Groups: <%= document.edit_groups.join(', ') %>
          <br/>
        <% end %>
        Users: <%= document.edit_people.join(', ') %>
      </dd>
    </dl>
  </td>
</tr>

app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb
<%
  def draw_tree(node)
    nested = node.nested_collection_names_and_links
    nested.each do |nest|
      nest.each_with_index do |col,index|
        unless index == 0
         %>
         /
         <%
        end
%>
       <strong><%= link_to col[:title], dashboard_collection_path(col[:id]) %></strong>
<%
      end
%>
     <br/>
<%
    end
  end
%>

<% if presenter.total_parent_collections <= 0 %>
  <div class="alert alert-warning" role="alert"><%= t('hyrax.collections.show.no_visible_parent_collections') %></div>
<% else %>
<% draw_tree(presenter) %>
<% if false %>
  <ul class="collections-list">
    <% presenter.parent_collections.documents.each do |document| %>
      <%= render 'hyrax/dashboard/collections/show_parent_collection_row', id: presenter.id, document: document %>
    <% end %>
  </ul>
<% end %>
  <div class="row">
    <%= render 'hyrax/collections/paginate', solr_response: presenter.parent_collections, page_param_name: :parent_collection_page %>
  </div>
  <!-- Remove parent collection Modal window -->
  <%= render 'modal_remove_from_collection' %>
<% end %>

app/views/hyrax/dashboard/collections/show.html.erb
<% provide :page_title, construct_page_title(@presenter.title) %>

<% provide :page_header do %>
  <h1><span class="fa fa-file" aria-hidden="true"></span> <%= t('.header') %></h1>
<% end %>

<div class="collections-wrapper">
  <section class="panel panel-default collections-panel-wrapper admin-show-page">
    <div class="panel-heading">
      <%= render 'collection_title', presenter: @presenter %>
    </div>

    <div class="panel-body">
      <section>
        <div itemscope itemtype="http://schema.org/CollectionPage" class="row collection">
          <div class="col-sm-3 text-center">
              <%= render 'hyrax/collections/media_display', presenter: @presenter %>
              <%= link_to t('.public_view_label'), collection_path(id: @presenter.id) %>
          </div>
          <div class="col-sm-9 collection-description-wrapper">
            <!-- Parent Collection(s) -->
            <% if @presenter.collection_type_is_nestable? && @presenter.total_parent_collections > 0 %>
                <h4><%= t('.parent_collection_header') %> </h4>
                <section id="parent-collections-wrapper" class="parent-collections-wrapper">
                  <%= render 'hyrax/dashboard/collections/show_parent_collections', presenter: @presenter %>
                </section>
            <% end %>

            <!-- Collection Description(s) -->
            <section>
              <%= render 'hyrax/collections/collection_description', presenter: @presenter %>
            </section>

            <% unless has_collection_search_parameters? %>
              <%= render 'show_descriptions' %>
            <% end %>
          </div>
        </div>
      </section>

      <!-- Search results label -->

      <% if @members_count > 0 || @presenter.subcollection_count > 0 %>
          <div class="hyc-blacklight hyc-bl-title">
            <h2>
              <% if has_collection_search_parameters? %>
                  <%= t('hyrax.dashboard.collections.show.search_results') %>
              <% end %>
            </h2>
          </div>
      <% end %>

      <!-- Search bar -->
      <section class="collections-search-wrapper">
        <div class="row">
          <div class="col-sm-8">
            <%# TODO: leaving this as it was causes rerouting to the public show page. needs work %>
            <%= render 'hyrax/collections/search_form', presenter: @presenter, url: hyrax.dashboard_collection_path(@presenter.id) %>
          </div>
        </div>
      </section>

      <!-- Subcollections -->
      <% if @presenter.collection_type_is_nestable? %>
        <section id="sub-collections-wrapper" class="sub-collections-wrapper">
          <h4><%= t('.subcollection_count') %> (<%= @subcollection_count %>)</h4>
          <div class="row">
            <div class="col-md-7">
              <%= render 'subcollection_list', id: @presenter.id, collection: @subcollection_docs %>
            </div>
            <% unless has_collection_search_parameters? %>
              <div class="col-md-5">
                <%= render 'show_subcollection_actions', presenter: @presenter %>
              </div>
            <% end %>
          </div>
        </section>
      <% end %>

      <!-- Works -->
      <section class="works-wrapper">
        <h4><%= t('.item_count') %> (<%= @members_count %>)</h4>
        <% unless has_collection_search_parameters? %>
          <%= render 'show_add_items_actions', presenter: @presenter %>
        <% end %>

        <%= render 'sort_and_per_page', collection: @presenter %>
        <%= render_document_index @member_docs %>
        <%= render 'hyrax/collections/paginate' %>
      </section>

    </div><!-- /panel-body -->
  </section><!-- /collections-panel-wrapper -->
</div><!-- /collections-wrapper -->

<% if @presenter.collection_type_is_nestable? && !has_collection_search_parameters? %>
  <%= render 'hyrax/my/collections/modal_add_to_collection', source: 'show' %>
  <%= render 'hyrax/my/collections/modal_add_subcollection', id: @presenter.id, source: 'show' %>
  <%= render 'hyrax/dashboard/collections/modal_parent_collection_remove_deny', source: 'show' %>
<% end %>

<% unless has_collection_search_parameters? %>
  <%= render '/shared/select_work_type_modal', create_work_presenter: @presenter.create_work_presenter if @presenter.draw_select_work_modal? %>
<% end %>